### ISSUE TITLE
readArea() and writeArea() with data length greater than pdu-size: wrong content

### ISSUE THREAD

**Issue by pmamod** [st-one-io/nodes7#3]
First of all: Great work! Thank you.

But I found a bug in file s7endpoint.js at line 538 in function readArea(): The offset (ptr) doesn't be added to address. So every iteration we read at the same start adress.
v1.0.0:
`address: address,`
my **solution**:
`address: address + ptr,`

Same bug (and fix) in function writeArea() at line 704.

Could you fix this in your code base an publish as a new version? Thanks!

**Comment by gfcittolin** [comment]
Hi there, just published 1.0.1 with the fix for that. Thanks for catching it and for the report!

**Comment by pmamod** [comment]
> Hi there, just published 1.0.1 with the fix for that. Thanks for catching it and for the report!

Thanks for the very quick fix!
